#!/usr/bin/env node
// Generates the committed route manifest for the admin Sitemap page
// (apps/admin/src/generated/sitemap.json). Scans every frontend app's App-Router
// pages and derives their URLs, so the admin — which can't read sibling apps at
// runtime (each is its own Vercel project) — can render the whole product's page
// surface from static data.
//
// Regenerate with `pnpm gen:sitemap` after adding/removing any app `page.tsx`.
// A staleness test (super/sitemap/sitemap-manifest.test.ts) fails CI if the commit
// drifts from the on-disk routes.
//
// URL derivation (Next App Router): route groups `(x)` are stripped, dynamic
// segments `[id]`/`[...slug]` kept, `page.tsx` = one route, `src/app/page.tsx` = `/`.

import { existsSync, mkdirSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

// The frontend apps to scan, with their production hosts (the two marketing apps
// aren't `<app>.<root>` subdomains, so they can't be derived from the admin host).
const APPS = [
  { key: "admin", label: "Admin", prodUrl: "https://admin.uprise.org.au" },
  { key: "auth", label: "Auth & SSO", prodUrl: "https://auth.uprise.org.au" },
  { key: "action", label: "Action", prodUrl: "https://action.uprise.org.au" },
  { key: "product-marketing", label: "Product marketing", prodUrl: "https://uprise.org.au" },
  { key: "organisation-marketing", label: "Uprise Labs", prodUrl: "https://upriselabs.org" },
  { key: "field", label: "Field PWA", prodUrl: "https://field.uprise.org.au" },
];

const isGroup = (seg) => seg.startsWith("(") && seg.endsWith(")");

/** Derive one route record from a page.tsx path relative to the app's `src/app`. */
function routeFromRel(relDir) {
  const segs = relDir === "" || relDir === "." ? [] : relDir.split("/");
  const groups = segs.filter(isGroup).map((s) => s.slice(1, -1));
  const urlSegs = segs.filter((s) => !isGroup(s));
  const path = urlSegs.length ? `/${urlSegs.join("/")}` : "/";
  return { path, dynamic: path.includes("["), group: groups.length ? groups.join(" › ") : null };
}

/** Walk an app's `src/app` for every page.tsx → sorted route records. Exported for the test. */
export function deriveRoutes(appDir) {
  const appRoot = join(appDir, "src", "app");
  if (!existsSync(appRoot)) return [];
  const routes = [];
  const walk = (dir) => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      if (entry.name === "node_modules" || entry.name.startsWith(".")) continue;
      const full = join(dir, entry.name);
      if (entry.isDirectory()) walk(full);
      else if (entry.isFile() && entry.name === "page.tsx") routes.push(routeFromRel(relative(appRoot, dir).split("\\").join("/")));
    }
  };
  walk(appRoot);
  // De-dupe (defensive) + stable order.
  const seen = new Set();
  return routes
    .filter((r) => (seen.has(r.path) ? false : seen.add(r.path)))
    .sort((a, b) => a.path.localeCompare(b.path));
}

export function buildManifest() {
  const apps = APPS.map((app) => {
    const routes = deriveRoutes(join(ROOT, "apps", app.key));
    return { ...app, routeCount: routes.length, routes };
  }).filter((a) => a.routeCount > 0);
  return { apps };
}

// Run as a script (skip when imported by the test).
if (process.argv[1] && process.argv[1].endsWith("gen-sitemap.mjs")) {
  const { apps } = buildManifest();
  const manifest = {
    $comment:
      "GENERATED by scripts/gen-sitemap.mjs — do not edit by hand. Run `pnpm gen:sitemap` after adding/removing any app page.tsx.",
    generatedAt: new Date().toISOString(),
    apps,
  };
  const out = join(ROOT, "apps", "admin", "src", "generated", "sitemap.json");
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, `${JSON.stringify(manifest, null, 2)}\n`);
  const total = apps.reduce((n, a) => n + a.routeCount, 0);
  console.log(`Wrote ${relative(ROOT, out)} — ${apps.length} apps, ${total} routes`);
  for (const a of apps) console.log(`  ${a.key.padEnd(24)} ${a.routeCount}`);
}
